apiVersion : apps/v1
kind: Deployment
metadata:
  name: mdt-cifra
  labels:
    app: mdt-cifra
spec:
  selector:
    matchLabels:
      project: mdt1
  template:
    metadata:
      labels:
        project: mdt1
    spec:
      containers: 
        - name : mdtcifra
          image: 404smoke/mdt-cifra:latest
          ports:
            - containerPorts: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: mdt-cifra-srv
  labels:
    env: test
    owner: 404smoke
spec:
  selector:
    project: mdt1
  ports:
    - name: app-listener
      protocol  : TCP
      port      : 80
      targetPort: 8080
    type: LoadBalancer
