apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdt-cifra
  labels:
    app: mdt-cifra
spec:
  replicas: 1
  selector:
    matchLabels:
      project: mdt1
  template:
    metadata:
      labels:
        project: mdt1
    spec:
      containers:
        - name: mdtcontainer
          image: 404smoke/mdt-cifra:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mdtservice
  labels:
    env: test
    owner: 404smoke
spec:
  selector:
    project: mdt1
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
